<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFeYj7UH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFeYj7UH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFeYj7UH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFeYj7UH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFeYj7UH\App_KernelDevDebugContainer([
    'container.build_hash' => 'FeYj7UH',
    'container.build_id' => 'beb6abe9',
    'container.build_time' => 1666715104,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFeYj7UH');
